"""empty message

Revision ID: 4757ae371707
Revises: 
Create Date: 2023-04-26 09:52:47.322198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4757ae371707'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('joke',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombreChiste', sa.String(length=250), nullable=True),
    sa.Column('textoChiste', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('joke')
    # ### end Alembic commands ###
